[project]
name = "moducomp"
version = "0.6.0"
description = "moducomp for computing metabolic module completeness and complementarity"
authors = ["Juan C. Villada <jvillada@lbl.gov>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tasks]
help = "./moducomp.py --help"
pipeline = { cmd = "./moducomp.py pipeline --help", cwd = "." }
analyze_kos = { cmd = "./moducomp.py analyze_kos --help", cwd = "." }

[dependencies]
python = ">=3.9,<3.12"
pandas = ">=1.5,<2.3"
typer = ">=0.9.1,<0.10.0"
click = "~=8.0.0" # Pinned to a version known to be compatible
eggnog-mapper = ">=2.1.9,<2.2.0"
kegg-pathways-completeness = "*"