context:
  version: 0.7.45

package:
  name: moducomp
  version: ${{ version }}

source:
- url: https://files.pythonhosted.org/packages/94/fc/5dae7a31f039be08902c438c097b08e178340c8ce7100596881aafa34fa3/moducomp-0.7.45.tar.gz
  sha256: acbdf9dbae77523e8cff579f5c33fad19cdb8ca768bdaee2a464e16d28e135fb

build:
  script:
    - ${{ PYTHON }} -m pip install .
  python:
    entry_points:
    - moducomp = moducomp.moducomp:app
  noarch: python

requirements:
  host:
  - python >=3.9,<3.12
  - flit >=3.2,<4
  - pip
  run:
  - python >=3.9,<3.12
  - typer >=0.9.1,<0.10.0
  - pandas >=1.5,<2.3
  - click ~=8.0.0
  - eggnog-mapper >=2.1.9,<2.2.0
  - kegg-pathways-completeness

tests:
- python:
    imports:
    - moducomp
    pip_check: true

about:
  summary: "moducomp: metabolic module completeness and complementarity in microbiomes"
  description: |-
    # moducomp

    moducomp is a bioinformatics pipeline for metabolic module completeness
    and metabolic complementarity analysis in microbiomes. It annotates proteins
    with eggNOG-mapper, maps KOs to KEGG modules, and reports completeness and
    complementarity across genome combinations.
  license: BSD-3-Clause
